name: Keep Render API Alive

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch: # allow manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://kohthmey-strapi-api.onrender.com/api/jobs
          curl -s -o /dev/null -w "%{http_code}" https://kohthmey-strapi-api.onrender.com/api/applications
          curl -s -o /dev/null -w "%{http_code}" https://kohthmey-strapi-api.onrender.com/api/contact-messages
